#!/bin/sh

xrdb -merge .Xresources

xsettingsd &

xsetroot -cursor_name left_ptr &


# TODO: We probably want to set other Touchpad options and find a
# better place to set these properties
# NOTE: The value here seems to be dependant on drivers provided
# by the distribution. Fedora had a diffeent name.
xinput set-prop "ELAN06FA:00 04F3:31DD Touchpad" "libinput Tapping Enabled" 1 &



#[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap

# Auto start all XDG defined startup apps
#dex-autostart --autostart --environment Xmonad

# Hide the Mouse when not in use
#unclutter &

# TODO: Make sure we store different profiles with autorandr
# Right now running this at the start will cause the external
# monitor to be at MAX resolution (which is not good due to scaling)
# We want that whatever is connected at startup is active
# Detect connected Monitors
#autorandr -c --default horizontal --skip-options crtc

# TODO: This is something I definitely want to review. Last
# time I tested this it was choppy and sound was aweful
# Cute sound for startup
#ffplay -nodisp -autoexit /opt/system_sounds/startup-01.mp3


{
	echo DISPLAY="$DISPLAY"
	echo XDG_SEAT="$XDG_SEAT"
	echo XDG_SESSION_ID="$XDG_SESSION_ID"
	echo XDG_VTNR="$XDG_VTNR"
} >"$XDG_RUNTIME_DIR"/xsession-env-"$DISPLAY"




# exec xmonad

# TODO: Eventually we may migrate to other WM (ie. Qtile). We may
# want to parameterize settings here and not hardcode Xmonad
if [[ "$(loginctl show-user --property=Display "$USER")" == "Display=$XDG_SESSION_ID" ]]; then
    echo "STARTING X ON FIRST OPTION" >> ~/login.txt
	systemctl --user import-environment SSH_AUTH_SOCK
	systemd-run \
		--collect --wait \
		--user --slice="session.slice" --unit="xmonad-$XDG_SESSION_ID-$DISPLAY.service" \
		--property="EnvironmentFile=$XDG_RUNTIME_DIR/xsession-env-$DISPLAY" \
		--property="Environment=_JUANK_SESSION_PRIMARY=1" \
		--property="Requires=graphical-session-pre.target" \
		--property="After=graphical-session-pre.target" \
		--property="BindsTo=graphical-session.target" \
		--property="BindsTo=xmonad@$DISPLAY.target" \
		--property="OnFailure=failsafe-xsecurelock@$DISPLAY.service" \
		--property="Restart=on-failure" \
		-- xmonad
else
    echo "STARTING X ON SECOND OPTION" >> ~/login.txt
	systemd-run \
		--quiet \
		--collect --scope \
		--user --slice="session.slice" --unit="xmonad-$XDG_SESSION_ID-$DISPLAY.scope" \
		--property="BindsTo=xmonad@$DISPLAY.target" \
		-- xmonad
fi

systemctl --user start "failsafe-xsecurelock@$DISPLAY.service"
sleep 2
