#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="emacs,tmux,xinit,xsession,xprofile"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$(pwd)
fi

STOW_FOLDERS=$STOW_FOLDERS

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo ">>> stow $folder"
    stow -D $folder --target ~/ --dotfiles
    stow $folder --target ~/ --dotfiles
done
popd



echo ">>> stow .config"
stow -D dot-config --target ~/.config  --dotfiles
stow dot-config --target ~/.config --dotfiles
