#!/usr/bin/env bash

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="emacs,tmux,xsession,profile,gtk"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$(pwd)
fi

STOW_FOLDERS=$STOW_FOLDERS

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo ">>> stow $folder"
    stow -D $folder --target ~/ --dotfiles
    stow $folder --target ~/ --dotfiles
done
popd



echo ">>> stow .config"
stow -D dot-config --target ~/.config  --dotfiles
stow dot-config --target ~/.config --dotfiles


mkdir -p ~/.local/bin


echo ">>> stow bin directory"
stow -D bin --target ~/.local/bin
stow bin --target ~/.local/bin
