[env]
TERM = "xterm-256color"

[terminal.shell]
program = "tmux"

[window]
padding.x = 16
padding.y = 14
#decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[font]
size=11
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }

# One Dark
# ========================================
# Default colors
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

# Doom One Theme
# ========================================    
# Default colors
#[colors.primary]
#background = '#282c34'
#foreground = '#bbc2cf'

# Normal colors
# [colors.normal]
# black   = '#282c34'
# red     = '#ff6c6b'
# green   = '#98be65'
# yellow  = '#ecbe7b'
# blue    = '#51afef'
# magenta = '#c678dd'
# cyan    = '#46d9ff'
# white   = '#bbc2cf'

# Gruvbox Theme
# ========================================    
# Default colors
# [colors.primary]
# background = '#282828'
# foreground = '#d4be98'

# # Normal colors
# [colors.normal]
# black   = '#3c3836'
# red     = '#ea6962'
# green   = '#a9b665'
# yellow  = '#d8a657'
# blue    = '#7daea3'
# magenta = '#d3869b'
# cyan    = '#89b482'
# white   = '#d4be98'

# [colors.bright]
# black   = '#3c3836'
# red     = '#ea6962'
# green   = '#a9b665'
# yellow  = '#d8a657'
# blue    = '#7daea3'
# magenta = '#d3869b'
# cyan    = '#89b482'
# white   = '#d4be98'

[terminal]
