#!/bin/sh

picom &
trayer --edge top --align right --widthtype percent --transparent true --alpha 0 --tint 0x282c34 --width 10 --height 24 &
xsettingsd &
shutter -min_at_startup &
nm-applet &
volumeicon &
ibus-daemon -drxR &
emacs --daemon &
xscreensaver -no-splash &
xfce4-power-manager &
autorandr -c &
nitrogen --restore &
